name: CI

on: [ push, pull_request ]

jobs:

    build:

        name: "Check"

        strategy:
            fail-fast: true
            matrix:
                os: [ ubuntu-latest, macos-latest, windows-latest ]

        runs-on: ${{ matrix.os }}

        steps:

            -   name: "git clone"
                uses: actions/checkout@v1

            -   name: "setup jdk"
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8

            -   name: "./gradlew build"
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: --scan --no-build-cache build
                env:
                    CI: true

            -   name: "git diff --exit-code"
                run: git diff --exit-code
